# Generated by Django 5.0.3 on 2024-04-10 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notesBody', models.TextField()),
                ('posX', models.FloatField(default=0)),
                ('posY', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('pinned', models.BooleanField(default=False)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='canvas.canvas')),
            ],
        ),
    ]
