# Generated by Django 5.0.3 on 2024-04-17 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canvas',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='canvas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
